name: Build Server

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install npm dependencies
        shell: cmd
        run: |
          npm ci || npm i

      - name: Compile
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          .scripts\compile-windows.cmd

      - name: Run tests
        shell: cmd
        run: |
          npm test

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          archive: false
          path: rmpsm_server.*

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Check package version
        run: bash ./.scripts/check-package-ver.sh

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install npm dependencies
        run: |
          npm ci || npm i

      - name: Compile
        run: |
          ./compile.sh
          cp native/bin/* .

      - name: Run tests
        run: |
          npm test

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          archive: false
          path: rmpsm_server.*

  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install npm dependencies
        run: |
          npm ci || npm i

      - name: Check package version
        run: bash ./.scripts/check-package-ver.sh

      - name: Compile
        run: |
          ./compile.sh android_aarch64 $ANDROID_NDK_LATEST_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang++ $ANDROID_NDK_LATEST_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip
          cp native/bin/* .

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          archive: false
          path: rmpsm_server.*
